# Disabling sudo moves build to the Container Based Infrastructure on Travis CI
sudo: false

jdk: oraclejdk8

script:
  - sh ci.sh

notifications:
  email: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
